/**
 * SDK Control Types — inferred from controlSchemas.ts Zod schemas.
 *
 * This file would normally be auto-generated by `bun scripts/generate-sdk-types.ts`.
 * Since the generator script is not available, these types are manually reconstructed
 * from the schema definitions and usage sites.
 */

import type { z } from 'zod/v4'
import type {
  SDKControlInitializeRequestSchema,
  SDKControlInitializeResponseSchema,
  SDKControlInterruptRequestSchema,
  SDKControlPermissionRequestSchema,
  SDKControlSetPermissionModeRequestSchema,
  SDKControlSetModelRequestSchema,
  SDKControlSetMaxThinkingTokensRequestSchema,
  SDKControlMcpStatusRequestSchema,
  SDKControlMcpStatusResponseSchema,
  SDKControlGetContextUsageRequestSchema,
  SDKControlMcpSetServersRequestSchema,
  SDKControlMcpSetServersResponseSchema,
  SDKControlReloadPluginsRequestSchema,
  SDKControlReloadPluginsResponseSchema,
} from './controlSchemas.js'

// Re-export inferred types from control schemas
export type SDKControlInitializeRequest = z.infer<ReturnType<typeof SDKControlInitializeRequestSchema>>
export type SDKControlInitializeResponse = z.infer<ReturnType<typeof SDKControlInitializeResponseSchema>>
export type SDKControlInterruptRequest = z.infer<ReturnType<typeof SDKControlInterruptRequestSchema>>
export type SDKControlPermissionRequest = z.infer<ReturnType<typeof SDKControlPermissionRequestSchema>>
export type SDKControlSetPermissionModeRequest = z.infer<ReturnType<typeof SDKControlSetPermissionModeRequestSchema>>
export type SDKControlSetModelRequest = z.infer<ReturnType<typeof SDKControlSetModelRequestSchema>>
export type SDKControlSetMaxThinkingTokensRequest = z.infer<ReturnType<typeof SDKControlSetMaxThinkingTokensRequestSchema>>
export type SDKControlMcpStatusRequest = z.infer<ReturnType<typeof SDKControlMcpStatusRequestSchema>>
export type SDKControlMcpStatusResponse = z.infer<ReturnType<typeof SDKControlMcpStatusResponseSchema>>
export type SDKControlGetContextUsageRequest = z.infer<ReturnType<typeof SDKControlGetContextUsageRequestSchema>>
export type SDKControlMcpSetServersRequest = z.infer<ReturnType<typeof SDKControlMcpSetServersRequestSchema>>
export type SDKControlMcpSetServersResponse = z.infer<ReturnType<typeof SDKControlMcpSetServersResponseSchema>>
export type SDKControlReloadPluginsRequest = z.infer<ReturnType<typeof SDKControlReloadPluginsRequestSchema>>
export type SDKControlReloadPluginsResponse = z.infer<ReturnType<typeof SDKControlReloadPluginsResponseSchema>>

// Union of all control request types
export type SDKControlRequest =
  | SDKControlInitializeRequest
  | SDKControlInterruptRequest
  | SDKControlPermissionRequest
  | SDKControlSetPermissionModeRequest
  | SDKControlSetModelRequest
  | SDKControlSetMaxThinkingTokensRequest
  | SDKControlMcpStatusRequest
  | SDKControlGetContextUsageRequest
  | SDKControlMcpSetServersRequest
  | SDKControlReloadPluginsRequest

// Union of all control response types
export type SDKControlResponse =
  | SDKControlInitializeResponse
  | SDKControlMcpStatusResponse
  | SDKControlMcpSetServersResponse
  | SDKControlReloadPluginsResponse

// Stdout message type for structured output
import type { StdoutMessageSchema } from './controlSchemas.js'
export type StdoutMessage = z.infer<ReturnType<typeof StdoutMessageSchema>>
